query {
  theming {
    config {
      theme
      iconset
      darkMode
      tocPosition
      loadingAnimation
      loadingColor
      loadingSpeed
      injectCSS
      injectHead
      injectBody
    }
  }
}
