query {
  system {
    info {
      configFile
      cpuCores
      currentVersion
      dbHost
      dbType
      dbVersion
      gitBranch
      gitCommit
      gitCommitDate
      hostname
      latestVersion
      latestVersionReleaseDate
      nodeVersion
      operatingSystem
      platform
      ramTotal
      upgradeCapable
      workingDirectory
    }
  }
}
